// <auto-generated/>
using System.CodeDom.Compiler;
using System.ComponentModel;

namespace BagsForEveryone
{
    [GeneratedCode("BepInEx.PluginInfoProps", "1.0.0.0")]
    [EditorBrowsable(EditorBrowsableState.Never)]
    internal static class MyPluginInfo
    {
        public const string PLUGIN_GUID = "com.nozz.bagsforeveryone";
        public const string PLUGIN_NAME = "BagsForEveryone";
        public const string PLUGIN_VERSION = "1.0.0";
    }
}